
pro: main.o print.o delete.o erase.o add.o search.o
		gcc -o pro main.o print.o delete.o erase.o add.o search.o
main.o: main.c
		gcc -c main.c -o main.o
print.o: print.c
		gcc -c print.c -o print.o
erase.o: erase.c
		gcc -c erase.c -o erase.o
add.o: add.c
		gcc -c add.c -o add.o
delete.o: delete.c
		gcc -c delete.c -o delete.o
search.o: search.c
		gcc -c search.c -o search.o
