/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>

/*
 * Stack Operations
 */

#define SRAM_START  	0x20000000U
#define SRAM_SIZE		(64 * 1024)
#define STACK_START		((SRAM_START) + (SRAM_SIZE))

#define STACK_MSP_START	STACK_START
#define STACK_MSP_END	(STACK_MSP_START + 512)
#define STACK_PSP_START STACK_MSP_END

int func_add(int a, int b, int c, int d)
{
	return a+b+c+d;
}

void generate_exception(void)
{
	__asm volatile("SVC #0x2");
}

void changeStackPointerToPSP(void)
{
	__asm volatile(".equ SRAM_END, (0x20000000 + (64*1024))");
	__asm volatile(".equ PSP_START, (SRAM_END-512)");

	//Load PSP with valid stack address
	__asm volatile("LDR R0, =PSP_START");
	__asm volatile("MSR PSP, R0");

	//Modify SPSEL bit of CONTROL register to 1 i.e sp uses PSP
	__asm volatile("MOV R0, #0x02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("BX LR");
}

/* This function executes in THREAD MODE of the processor */
int main(void)
{
	printf("In Stack Operation example !!!\n");
	changeStackPointerToPSP();
	int ret;

	ret = func_add(1, 4, 6, 9);

	printf("return = %d\n",ret);

	generate_exception();

	for(;;);
}

void SVC_Handler(void)
{
	printf("in SVC_Handler\n");
}
