/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>


/* This function executes in THREAD MODE of the processor */
int main(void)
{
//	printf("In thread mode : before interrupt\n");

// Commenting below code to test
#if 0
	/* Execute Assembly code in c*/
	__asm volatile("LDR R1, =#0x20001000");
	__asm volatile("LDR R2, =#0x20001004");
	__asm volatile("LDR R0, [R1]");
	__asm volatile("LDR R1, [R2]");
	__asm volatile("ADD R0,R0,R1");
	__asm volatile("STR R0,[R2]");
#endif

#if 0
	/* Move a c variable data to general purpose register */
	int val = 20;
	__asm volatile ("MOV R0, %0"::"r"(val):);
#endif

#if 0
	/* Move special purpose register value to a c variable*/
	int control_Register;
	__asm volatile ("MSR %0,CONTROL":"=r"(control_Register)::);
#endif

#if 0
	/* Move c variable1 to a c variable2 using inline assembly*/
	int var1=28,var2;
	__asm volatile ("MOV %0,%1":"=r"(var2):"r"(var1));
#endif

#if 1
	/* Copy contents of a pointer into a another variable using inline assembly i.e var = *p2 */
	//modify the data at 0x20000008 address via memory window
	int datavar, *ptr;
	ptr = (int*) 0x20000008;
	__asm volatile ("LDR %0,[%1]": "=r"(datavar):"r"(ptr));
#endif

	for(;;);

}


