
project: main.o print.o delete.o add.o erase.o
	gcc  -o pro  print.o delete.o main.o add.o erase.o
add.o: add.c 
	gcc -c add.c -o add.o
print.o: print.c 
	gcc -c print.c -o print.o
delete.o: delete.c 
	gcc -c delete.c -o delete.o
main.o: main.c 
	gcc -c main.c -o main.o
erase.o: erase.c 
	gcc -c erase.c -o erase.o


	         
