/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdint.h>
#include<stdio.h>

#define SVC_ADD		36
#define SVC_SUB		37
#define SVC_MUL		38
#define SVC_DIV		39


void SVC_Handler_c(int32_t operand1, int32_t operand2, uint32_t *pBaseStackFrame);

int main(void)
{
	int32_t op1 = 12, op2 = 10;
//    __asm volatile ("MOV r0, %0" : "=r"(op1) ::);
//    __asm volatile ("MOV r1, %0" : "=r"(op2) ::);
    __asm volatile ("MOV R0, %0"::"r"(op1):);
    __asm volatile ("MOV R1, %0"::"r"(op2):);

    __asm volatile("SVC #39");

//	register uint32_t data __asm("r0"); // request to GCC to store variable in R0 (not recommended)
    int32_t data;
    __asm volatile ("MOV %0, r0" : "=r"(data) ::);
    printf("data returned by %ld\r\n", data);

	//4.

	for(;;);
}


__attribute__ ((naked)) void SVC_Handler(void)
{
	//here we extracted the value of MSP which happens to be the
	//base address of the stack frame(thread mode) which got saved during the exception entry
	//from thread mode to handler mode
	__asm ("MRS r2,MSP");
	__asm ("B SVC_Handler_c");
}

void SVC_Handler_c(int32_t operand1, int32_t operand2, uint32_t *pBaseStackFrame)
{
	uint8_t *svc_addr = (uint8_t *)pBaseStackFrame[6];
//	int32_t operand1  = (int32_t)  pBaseStackFrame[0];
//	int32_t operand2  = (int32_t)  pBaseStackFrame[1];
	svc_addr -= 2;
	uint8_t svc_num = *svc_addr;
//	printf("Exception : SVC_Handler\n");
	printf("SVC number is %d\n", svc_num);
//	svc_num += 4;
	switch(svc_num)
	{
		case SVC_ADD:
			pBaseStackFrame[0] = (operand1 + operand2);
			break;
		case SVC_SUB:
			pBaseStackFrame[0] = (operand1 - operand2);
			break;
		case SVC_MUL:
			pBaseStackFrame[0] = (operand1 * operand2);
			break;
		case SVC_DIV:
			pBaseStackFrame[0] = (operand1 / operand2);
			break;
		default:
			pBaseStackFrame[0] = 0;
			printf("Invalid SVC Number %d\n", svc_num);
			break;
	};

//	pBaseStackFrame[0] = svc_num;
//	printf("Exception : SVC_Handler2\n");

//	printf("pBaseStackFrame = %p\n",pBaseStackFrame);
//	printf("Value of R0 = %lx\n", pBaseStackFrame[0]);
//	printf("Value of R1 = %lx\n", pBaseStackFrame[1]);
//	printf("Value of R2 = %lx\n", pBaseStackFrame[2]);
//	printf("Value of R3 = %lx\n", pBaseStackFrame[3]);
//	printf("Value of R12 = %lx\n", pBaseStackFrame[4]);
//	printf("Value of LR = %lx\n", pBaseStackFrame[5]);
//	printf("Value of PC = %lx\n", pBaseStackFrame[6]);
//	printf("Value of XPSR = %lx\n", pBaseStackFrame[7]);
//	printf("SVC number is %x", *(((uint8_t *) pBaseStackFrame[6] - 2)));
//	while(1);
}

