/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdint.h>
#include<stdio.h>

void UsageFault_Handler_c(uint32_t *pMSP);

int main(void)
{
	//1.

	__asm volatile("SVC #8");


	//4.

	for(;;);
}


__attribute__ ((naked)) void SVC_Handler(void)
{
	//here we extracted the value of MSP which happens to be the
	//base address of the stack frame(thread mode) which got saved during the exception entry
	//from thread mode to handler mode
	__asm ("MRS r0,MSP");
	__asm ("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pBaseStackFrame)
{
	uint8_t *svc_addr = (uint8_t *)pBaseStackFrame[6];
	svc_addr -= 2;
	uint8_t svc_num = *svc_addr;
//	printf("Exception : SVC_Handler\n");
	printf("SVC number is %d\n", svc_num);
	printf("Exception : SVC_Handler2\n");

//	printf("pBaseStackFrame = %p\n",pBaseStackFrame);
//	printf("Value of R0 = %lx\n", pBaseStackFrame[0]);
//	printf("Value of R1 = %lx\n", pBaseStackFrame[1]);
//	printf("Value of R2 = %lx\n", pBaseStackFrame[2]);
//	printf("Value of R3 = %lx\n", pBaseStackFrame[3]);
//	printf("Value of R12 = %lx\n", pBaseStackFrame[4]);
//	printf("Value of LR = %lx\n", pBaseStackFrame[5]);
//	printf("Value of PC = %lx\n", pBaseStackFrame[6]);
//	printf("Value of XPSR = %lx\n", pBaseStackFrame[7]);
//	printf("SVC number is %x", *(((uint8_t *) pBaseStackFrame[6] - 2)));
	while(1);
}

