
pro:   main.o print.o delete.o add.o search.o cut.o
		gcc -o pro  main.o print.o delete.o add.o search.o cut.o

main.o: main.c
		gcc -c main.c -o main.o
print.o: print.c
	        gcc -c print.c -o print.o
delete.o: delete.c
		gcc -c delete.c -o delete.o
add.o: add.c
		gcc -c add.c -o add.o
search.o: search.c
	 	gcc -c search.c -o search.o
cut.o: cut.c 
		gcc -c cut.c -o cut.o
