/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>


#define USART6_IRQ_NO	71

/* This function executes in THREAD MODE of the processor */
int main(void)
{
	printf("In USART6 Interrupt Pend example !!!\n");

	/* 1) Manually pend the pending bit for USART6 IRQ number in NVIC */
	int * pISPR2 = 0XE000E200 + (2*4);

	*pISPR2 |= 1 << (USART6_IRQ_NO % 32);
	/* 2) Enable the USART6 IRQ number(71) in NVIC */
	int * pISER2 = 0xE000E100 + (2*4);

	*pISER2 |= 1 << (USART6_IRQ_NO % 32);


	for(;;);
}

void USART6_IRQHandler()
{
	printf("In USART6_IRQHandler !!!\n");
}

