
pro: main.o btoi.o input.o print.o 
	gcc -o pro main.o btoi.o input.o print.o

main.o:main.c 	
	gcc -c main.c -o main.o
btoi.o:btoi.c 	
	gcc -c btoi.c -o btoi.o
input.o:input.c 	
	gcc -c input.c -o input.o
print.o:print.c 	
	gcc -c print.c -o print.o
