/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>

/*
 * Bit Banding:
 * 0x2200 0000 ---> 0x2000 0000 (bit 0)
 * 0x2200 0004 ---> 0x2000 0000 (bit 1)
 * 0x2200 0008 ---> 0x2000 0000 (bit 2)
 * 0x2200 000C ---> 0x2000 0000 (bit 3)
 * 0x2200 0010 ---> 0x2000 0000 (bit 4)
 * 0x2200 0014 ---> 0x2000 0000 (bit 5)
 * 0x2200 0018 ---> 0x2000 0000 (bit 6)
 *  ...
 * 0x2200 007C ---> 0x2000 0000 (bit 31)
 * 0x2200 0080 ---> 0x2000 0001 (bit 0)
 *  ...
 * Note: Bit Banding is atomic operation to bit data
 * base address = 0x2200 0000 // 2.2 section of pm0214
 * Alias Address = alias_base + (32 *(bit_band_memory_add - bit_band_base)) + bit * 4
 */

#define alias_base  	(0x22000000)
#define bit_band_base	(0x20000000)

#define bit_band_memory_addr_to_be_Written	0x20000200
#define bit_to_be_Written					0x7

/* This function executes in THREAD MODE of the processor */
int main(void)
{
	printf("In BitBand Example:\n");
	// calculate the bit band alias address of 7th bit position of 0x2000 0200
	uint8_t * ptr = (uint8_t *) bit_band_memory_addr_to_be_Written;
	*ptr = 0xFF;
	//normal method to clear 7th bit which involves read-modify-write
	*ptr &= (~(1 << 7));

	// reset the value at pointer location
	*ptr = 0xFF;

	//Bit-Banding
	uint8_t * AliasAddress = (uint8_t *) (alias_base + (32 * (bit_band_memory_addr_to_be_Written - bit_band_base)) + bit_to_be_Written * 4);
	printf("AliasAddress:%x\n", AliasAddress);
	*AliasAddress = 0;
	printf("value=%x\n",*ptr);
	for(;;);
}


void HardFault_Handler(void)
{
	printf("Hard Fault has been detected\n");
	while(1);
}
