
pro: main.o input.o print.o sum.o 
	gcc -o pro main.o input.o print.o sum.o

main.o:main.c 	
	gcc -c main.c -o main.o
input.o:input.c 	
	gcc -c input.c -o input.o
print.o:print.c 	
	gcc -c print.c -o print.o
sum.o:sum.c 	
	gcc -c sum.c -o sum.o

