/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>

uint32_t*  pNVIC_ISER_BASE_ADDR = (uint32_t *) 0xE000E100;
uint32_t*  pNVIC_ISPR_BASE_ADDR = (uint32_t *) 0XE000E200;
uint32_t*  pNVIC_IPR_BASE_ADDR 	= (uint32_t *) 0xE000E400;

void configureIrqPriority(uint8_t irq, uint8_t priority)
{
	uint8_t   iprx = irq / 4;
	uint32_t* ipr  = pNVIC_IPR_BASE_ADDR + iprx;
	uint8_t   pos  =  (irq % 4) * 8;
	/* clear previous priority */
	*(ipr) &= ~(0xFF << pos);
	/* set priority */
	*(ipr) |= (priority << pos);
}

#define IRQNO_TIMER2	28
#define IRQNO_I2C1  	31

/* This function executes in THREAD MODE of the processor */
int main(void)
{
	printf("In Interrupt Priority example !!!\n");

	/* 1) Configure the Priority for the peripherals */
	configureIrqPriority(IRQNO_TIMER2, 0x80);
	//	configureIrqPriority(IRQNO_I2C1, 0x80);
	configureIrqPriority(IRQNO_I2C1, 0x70);

	/* 2) Set the Interrupt bit in NVIC PR */
	*pNVIC_ISPR_BASE_ADDR |= (1 << IRQNO_TIMER2);
//	*pNVIC_ISPR_BASE_ADDR |= (1 << IRQNO_I2C1);

	/* 3) Enable the IRQ in NVIC ISER */
	*pNVIC_ISER_BASE_ADDR |= (1 << IRQNO_I2C1);
	*pNVIC_ISER_BASE_ADDR |= (1 << IRQNO_TIMER2);
//	*pNVIC_ISER_BASE_ADDR |= (1 << IRQNO_I2C1);

	for(;;);
}

void TIM2_IRQHandler()
{
	printf("In TIM2_IRQHandler pNVIC_ISPR_BASE_ADDR=%p !!!\n", pNVIC_ISPR_BASE_ADDR);
	*pNVIC_ISPR_BASE_ADDR |= (1 << IRQNO_I2C1);
	while(1);
}

void TIM3_IRQHandler()
{
	printf("In TIM3_IRQHandler !!!\n");
}

void I2C1_EV_IRQHandler()
{
	printf("In I2C1_EV_IRQHandler !!!\n");
}



